# Generated by Django 5.2.8 on 2025-11-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_order_15f442_idx',
            old_name='inventory_c_order_5e8a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_is_acti_63d81f_idx',
            old_name='inventory_c_is_acti_a9e7d0_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_sku_f85905_idx',
            old_name='inventory_p_sku_3f7b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_name_f6a6a1_idx',
            old_name='inventory_p_name_8c4f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='inventory_p_sku_b99cfb_idx',
            old_name='inventory_p_sku_variant_7e5d3b_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='inventory_p_product_f362c2_idx',
            old_name='inventory_p_product_active_9a2c4f_idx',
        ),
    ]
