# Generated by Django 6.0.2 on 2026-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL (e.g. blueprint asset). Used when no local image is uploaded.', max_length=500, verbose_name='Image URL'),
        ),
    ]
