# Generated by Django 6.0.2 on 2026-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='List of allergen codes (e.g. ["gluten", "dairy", "eggs"]).', verbose_name='Allergens'),
        ),
    ]
