# Generated by Django 6.0.2 on 2026-03-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_allergens_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique code for blueprint seed categories', max_length=100, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('user', 'User Created'), ('blueprint', 'Blueprint Seed'), ('import', 'Imported')], default='user', max_length=20, verbose_name='Source'),
        ),
    ]
