# Generated by Django 6.0 on 2025-12-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_add_taxclass_and_default_tax_class'),
        ('inventory', '0002_rename_inventory_c_order_5e8a9c_idx_inventory_c_order_15f442_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tax_class',
            field=models.ForeignKey(blank=True, help_text='Default tax class for products in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='configuration.taxclass', verbose_name='Tax Class'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical Product'), ('service', 'Service')], default='physical', help_text='Physical products affect stock, services do not', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, help_text="Override the category's tax class (optional)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='configuration.taxclass', verbose_name='Tax Class Override'),
        ),
    ]
