# Generated by Django 5.2.8 on 2025-11-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productsconfig'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
