# Generated by Django 5.2.8 on 2025-01-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_table_alter_product_table'),
    ]

    operations = [
        # Rename ProductsConfig table
        migrations.RenameModel(
            old_name='ProductsConfig',
            new_name='InventoryConfig',
        ),
        migrations.AlterModelTable(
            name='inventoryconfig',
            table='inventory_config',
        ),
        # Rename Category table
        migrations.AlterModelTable(
            name='category',
            table='inventory_category',
        ),
        # Rename Product table
        migrations.AlterModelTable(
            name='product',
            table='inventory_product',
        ),
        # Update verbose names
        migrations.AlterModelOptions(
            name='inventoryconfig',
            options={'verbose_name': 'Inventory Configuration', 'verbose_name_plural': 'Inventory Configuration'},
        ),
    ]
