# Generated by Django 5.2.8 on 2025-01-21 12:10

from django.db import migrations


def rename_tables(apps, schema_editor):
    """Renombrar tablas existentes de products_* a inventory_*"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar si las tablas antiguas existen
        cursor.execute("""
            SELECT name FROM sqlite_master
            WHERE type='table' AND name IN ('products_config', 'products_category', 'products_product')
        """)
        existing_tables = [row[0] for row in cursor.fetchall()]

        # Renombrar cada tabla si existe
        if 'products_config' in existing_tables:
            cursor.execute("ALTER TABLE products_config RENAME TO inventory_config")

        if 'products_category' in existing_tables:
            cursor.execute("ALTER TABLE products_category RENAME TO inventory_category")

        if 'products_product' in existing_tables:
            cursor.execute("ALTER TABLE products_product RENAME TO inventory_product")


def reverse_rename_tables(apps, schema_editor):
    """Revertir el renombrado de tablas"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE inventory_config RENAME TO products_config")
        cursor.execute("ALTER TABLE inventory_category RENAME TO products_category")
        cursor.execute("ALTER TABLE inventory_product RENAME TO products_product")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_tables_to_inventory'),
    ]

    operations = [
        migrations.RunPython(rename_tables, reverse_rename_tables),
    ]
