# Generated by Django 5.2.8 on 2025-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_existing_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow products to have negative stock values (sell even when out of stock)')),
                ('low_stock_alert_enabled', models.BooleanField(default=True, help_text='Show alerts when products are low in stock')),
                ('auto_generate_sku', models.BooleanField(default=True, help_text='Automatically generate SKU for new products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Configuration',
                'verbose_name_plural': 'Inventory Configuration',
                'db_table': 'inventory_config',
            },
        ),
        migrations.DeleteModel(
            name='InventoryConfig',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_order_15f442_idx',
            old_name='products_ca_order_ac6215_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_is_acti_63d81f_idx',
            old_name='products_ca_is_acti_a2d000_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_sku_f85905_idx',
            old_name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_name_f6a6a1_idx',
            old_name='products_pr_name_9ff0a3_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_categor_607069_idx',
            old_name='products_pr_categor_9edb3d_idx',
        ),
    ]
