# Generated by Django 5.2.8 on 2025-11-21 19:23

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Remove index only if it exists (handle SQLite gracefully)"""
    if schema_editor.connection.vendor == 'sqlite':
        # Check if index exists in SQLite
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='index' AND name='inventory_p_categor_607069_idx'
            """)
            if cursor.fetchone():
                cursor.execute("DROP INDEX inventory_p_categor_607069_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productsconfig_delete_inventoryconfig_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías del producto (puede pertenecer a múltiples)', related_name='products', to='inventory.category', verbose_name='Categorías'),
        ),
    ]
