# Generated by Django 5.2.8 on 2025-11-21 19:54

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Remove index only if it exists (handle SQLite gracefully)"""
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='index' AND name='inventory_p_categor_607069_idx'
            """)
            if cursor.fetchone():
                cursor.execute("DROP INDEX inventory_p_categor_607069_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_inventory_p_categor_607069_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
    ]
