# Generated by Django 5.2.8 on 2025-11-21 20:50

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Remove index only if it exists (handle SQLite gracefully)"""
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='index' AND name='inventory_p_categor_607069_idx'
            """)
            if cursor.fetchone():
                cursor.execute("DROP INDEX inventory_p_categor_607069_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_inventory_p_categor_607069_idx'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name='productsconfig',
            name='barcode_enabled',
            field=models.BooleanField(default=True, help_text='Enable barcode generation and printing for products'),
        ),
    ]
