# Generated by Django 5.2.8 on 2025-11-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_inventory_p_categor_607069_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_categor_607069_idx',
        ),
    ]
