# Generated by Django 5.2.8 on 2025-11-22 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_product_inventory_p_categor_607069_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: 'Rojo XL', 'Azul M', '1kg', '500ml'", max_length=255, verbose_name='Nombre de Variante')),
                ('sku', models.CharField(help_text='SKU único para esta variante', max_length=100, unique=True, verbose_name='SKU de Variante')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Atributos como {'color': 'rojo', 'talla': 'XL', 'peso': '1kg'}", verbose_name='Atributos')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio específico para esta variante (puede ser diferente al producto base)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Imagen de Variante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'inventory_product_variant',
                'ordering': ['product', 'name'],
                'indexes': [models.Index(fields=['sku'], name='inventory_p_sku_b99cfb_idx'), models.Index(fields=['product', 'is_active'], name='inventory_p_product_f362c2_idx')],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
