# Generated by Django 5.2.8 on 2025-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean13',
            field=models.CharField(blank=True, help_text='Código de barras EAN-13 (13 dígitos)', max_length=13, null=True, unique=True, verbose_name='EAN-13'),
        ),
    ]
